### ISSUE TITLE
Deserialize function receives: fatal error: runtime: out of memory 

### ISSUE THREAD

**Issue by smousa** [actgardner/gogen-avro#150]
Been seeing this when trying to deserialize an avro object from `bytes.NewBuffer`

```
goroutine 34 [running]:
github.com/actgardner/gogen-avro/v7/vm.readBytes(0xc06440, 0xc0003ef290, 0x1, 0x0, 0x0, 0x0, 0xc000409890)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/readers.go:38 +0x99 fp=0xc0001f4940 sp=0xc0001f48d8 pc=0x5b79a9
github.com/actgardner/gogen-avro/v7/vm.evalInner(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1b360, 0xc0000106d0, 0xc00050f7f8, 0x0, 0x0, 0x0)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:58 +0x423 fp=0xc0001f4ad0 sp=0xc0001f4940 pc=0x5b5e03
github.com/actgardner/gogen-avro/v7/vm.evalInner(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1bbe0, 0xc00038be50, 0xc00050f7f8, 0xc00021f650, 0x203000, 0x40e908)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:86 +0x8ad fp=0xc0001f4c60 sp=0xc0001f4ad0 pc=0x5b628d
github.com/actgardner/gogen-avro/v7/vm.evalInner(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1bbe0, 0xc00038be50, 0xc00050f7f8, 0x7fc0d21e1d00, 0x203000, 0x4168cf)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:112 +0xb55 fp=0xc0001f4df0 sp=0xc0001f4c60 pc=0x5b6535
github.com/actgardner/gogen-avro/v7/vm.evalInner(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1c360, 0xc00000f4a0, 0xc00050f7f8, 0x203000, 0x203000, 0x203000)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:86 +0x8ad fp=0xc0001f4f80 sp=0xc0001f4df0 pc=0x5b628d
github.com/actgardner/gogen-avro/v7/vm.evalInner(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1bde0, 0xc0003f3fa0, 0xc00050f7f8, 0x40, 0x179, 0x13c)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:86 +0x8ad fp=0xc0001f5110 sp=0xc0001f4f80 pc=0x5b628d
github.com/actgardner/gogen-avro/v7/vm.evalInner(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1bde0, 0xc0003f3fa0, 0xc00050f7f8, 0xc19f60, 0xc000408300, 0xc000109080)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:112 +0xb55 fp=0xc0001f52a0 sp=0xc0001f5110 pc=0x5b6535
github.com/actgardner/gogen-avro/v7/vm.Eval(0xc06440, 0xc0003ef290, 0xc000109080, 0xc1bde0, 0xc0003f3fa0, 0x0, 0x0)
	[...]/vendor/github.com/actgardner/gogen-avro/v7/vm/eval.go:30 +0xbd fp=0xc0001f5318 sp=0xc0001f52a0 pc=0x5b597d
```

**Comment by actgardner** [comment]
Hey @smousa, can you provide your schema and ideally some sample data that reproduces the issue? It's very difficult for me to diagnose without knowing what data you're deserializing. 

Also, what kind of environment is this? Docker container, your laptop, etc? How much memory does it have? It's totally possible this is a bug, but it could also just be that the data is very large to fit into memory.

**Comment by smousa** [comment]
Hi, thanks for the quick response...I think I solved at least part of the problem: I will open a pull request against master shortly

The other part of the problem may have to do with a schema mismatch on my end.  I will reopen the ticket if that is not the case.

Thanks!

**Comment by smousa** [comment]
https://github.com/actgardner/gogen-avro/pull/151
